### ISSUE TITLE
Phase false positives

### ISSUE THREAD

**Issue by zedwick** [Confuser2188/PAC#15]
## General Information

**PAC version** : 2.0.0-pre5

**Server version** : Paper version git-Paper-444 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

## Explanation of issue
The following blocks have false positives for Phase

Thee blocks can be completely phased through in vanilla:
 - OXEYE_DAISY
 - PINK_TULIP
 - WHITE_TULIP
 - ORANGE_TULIP
 - RED_TULIP
 - AZURE_BLUET
 - ALLIUM
 - PEONY
 - LILAC
 - TUBE_CORAL_FAN
 - BRAIN_CORAL_FAN
 - BUBBLE_CORAL_FAN
 - HORN_CORAL_FAN
 - DEAD_TUBE_CORAL_FAN
 - DEAD_BRAIN_CORAL_FAN
 - DEAD_BUBBLE_CORAL_FAN
 - DEAD_HORN_CORAL_FAN
 - BEETROOTS

The following blocks have have a slightly smaller collision box:
 - CONDUIT
 - END_ROD

These blocks have different collision boxes depending on their block states:
 - IRON_BARS
 - GLASS_PANE

This partially duplicates #14 and #11, but kept those two blocks here so you can see them all in one place.

**Comment by bigpresh** [comment]
Also seeing the same behaviour with the various buttons - e.g. 

`[20:29:26] [Server thread/INFO]: PAC: bigpresh failed Phase check [VL: 2] [Ping: 23] [Info: type:'edge' block:'DARK_OAK_BUTTON']`

Tested with stone, dark oak, birch, and acacia and all showed the same behaviour - but it only happens if the player is standing on a slab or carpet so that the button's hitbox intersects their upper body.

Just walking up to the button in a straight line is enough to trigger it.

Vanilla 1.13.2 client, server running Spigot 1.13.2 build 1993:

`git-Spigot-667bdd6-1b982fd (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT).`

Also, attempting to stand/walk on a cake bock placed on the ground also triggers the same phase errors - I'm assuming that all the ones mentioned in this ticket are all down to changes in how hitboxes work in 1.13?
